server {
    listen 80;
    
    # Directorio donde Vite genera los archivos
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Si no encuentra el archivo, sirve index.html (necesario para React Router SPA)
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Manejo de errores 404
    error_page 404 /index.html;
}
